config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'home/about'
  get 'home/test'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends</h1>

<table class="table table-dark table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="3"><center>Action</center></th>
    </tr>
  </thead>

  <tbody class=" table-striped ">
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><button class="btn success"><%= link_to 'Show', friend, class:"btn btn-success" %></button></td>
        <td><button class="btn warning"><%= link_to 'Edit', edit_friend_path(friend), class:"btn btn-warning" %></button></td>
        <td><button class="btn danger"><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Friend', new_friend_path, class: "btn btn-dark" %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>First name:</strong>
  <%= @friend.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @friend.twitter %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-dark" %> |
<%= link_to 'Back', friends_path, class: "btn btn-dark"  %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend App', root_path, class:'navbar-brand' %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Friends', friends_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Friend', new_friend_path, class:"nav-link" %>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us....</h1>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>This is my first web page....</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Friends App</title>
  </head>
  <body class="bg-info">
    <br/>
    <%= render 'home/header' %>
    <div class="container">
    <%= yield %>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>